spring:
  datasource:
    username: ${aws_db_username}
    password: ${aws_db_password}
    url: ${aws_db_url}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: validate
        # auto: create-drop
          # none or validate recommend on release DB
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 300MB